name: intl_phone_field_plus
description: A customised Flutter TextFormField to input international phone number along with country code. (Maintained fork)
version: 1.0.1
homepage: https://github.com/Doublefire-Chen/intl_phone_field_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  assets:
    - assets/flags/
